### ISSUE TITLE
Expression.py and matplotlib on cluster machines

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#186] opened 2015-05-26 16:56 UTC
Hi All,

Running any task which uses Expression.py on a machine that does not have X11 support, such as a cluster machine gives the following error:

```python-traceback

bin/bash: error importing function definition for `BASH_FUNC_module'
/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py:61: GtkWarning: IA__gdk_cursor_new_for_display: assertion `GDK_IS_DISPLAY (display)' failed
  cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
Traceback (most recent call last):
  File "/ifs/devel/Ian/cgat/scripts/runExpression.py", line 145, in <module>
    import CGAT.Expression as Expression
  File "/ifs/devel/Ian/cgat/CGAT/Expression.py", line 83, in <module>
    import ggplot
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/__init__.py", line 21, in <module>
     from .qplot import qplot
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/qplot.py", line 5, in <module>
    from .components import aes
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/components/__init__.py", line 4, in <module>
    from . import colors, shapes, size, linetypes, alphas
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/components/colors.py", line 6, in <module>
    from ..utils.color import ColorHCL
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/utils/__init__.py", line 4, in <module>
    from .ggutils import ggsave, add_ggplotrc_params
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/ggplot/utils/ggutils.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 61, in <module>
    cursors.MOVE          : gdk.Cursor(gdk.FLEUR),
RuntimeError: could not create GdkCursor object

```

This is due to the matplotlib backend trying to create X11 objects. I am currently testing a solution that will use a different matplotlib backend (the "Agg" backend). Does anyone see any reason why this shouldn't be okay?

**Comment by AndreasHeger** [comment] 2015-05-26 17:41
Hi Ian,

yes, setting the backend in matplotlibrc to Agg is what I usually do if 
I run plotting commands on the cluster. Ideally the backend could be set 
at runtime, but unfortunately that is tricky - there used to
be a strict sequence of imports which of course would need to be 
followed by every module importing matplotlib as you never know which 
module gets imported first.

Ciao,
Andreas

**Comment by IanSudbery** [comment] 2015-05-26 17:50
Hi @AndreasHeger 

The problem is that some of our modules now import pylab even if they aren't doing any plotting.

In Expression.py i'm trying setting the backend to agg before the pyplot or ggplot import:

```python
import matplotlib
matplotlib.use("agg")
... <SNIP> ...
import ggplot
... <SNIP> ...
import matplotlib.pyplot as plt
import pylab
```

Is there a reason I shouldn't do this?

**Comment by AndreasHeger** [comment] 2015-05-26 17:56
No. Any superfluous imports should be removed, pylab is one of them.

The problem with this that I can foresee is that our scripts will
not work on any system without Agg. Nor does it allow somebody to plot 
in svg, eps, pdf, etc. Thus the backend needs to be set-able from the 
commandline, which is probably as much hazzle as setting it in 
matplotlibrc and have the matplotlib engine initialize itself from there.

Best wishes,
Andreas

**Comment by IanSudbery** [comment] 2015-05-29 09:06
@AndreasHeger I think read somewhere that agg is installed as part of matplotlib as standard. By the way, it would be good if we could do this on CGATReport as well (or specifically cgatreport-test). Occasionally I need to test trackers without an X11 session.

**Comment by AndreasHeger** [comment] 2015-06-02 19:33
Thanks, @IanSudbery . However, the problem is that setting the backend to Agg will always override user choice. Using command line options might not be feasible in plotting that happens in modules.
Maybe we should wrap matplotlib so that a check is performed if plotting is possible and on exception sets the backend to Agg. 
I will look into this as well.

**Comment by AndreasHeger** [comment] 2015-08-12 12:27
Hi @IanSudbery, I had a bit of a look around, but it seems there is no good solution that would work in both scripts and modules.

I think the best option is to never use "matplotlib.use" but instead set the backend in the rc file. I have a script that does this for me:

```shell
#! /bin/sh
# set the matplotlib backend
#
# Usage:
#
# mplset Agg
# mplset GTKAgg
#
perl -p -i -e "s/^backend +:.*/backend : $1/" ~/.config/matplotlib/matplotlibrc
```

Unfortunately, this is only a global setting, so if you want to have interactive plotting while at the same time plotting on the cluster without X, you have a problem.

Best, 
Andreas

**Comment by AndreasHeger** [comment] 2015-11-16 17:16
Closing for now, please reopen if a solution presents itself.

**Closed by AndreasHeger** 2015-11-16 17:16 UTC
