### ISSUE TITLE
Feature request: ignore secondary alignments (at least for bam_vs_bed)

### ISSUE THREAD

**Issue by mebbert** [CGATOxford/cgat#324] opened 2017-04-07 21:50 UTC
Hi,

I've only used a couple of your tools a few times, but it would be helpful to have an option in bam_vs_bed to ignore secondary alignments. I'll take a peek at the code and see if I can do it real quick, otherwise I'll just remove them from my bams.

Thanks!

**Comment by AndreasHeger** [comment] 2017-04-10 15:57
Thanks, unfortunately that is not easily done. The script is very simplistic and simply runs bedtools multiple times and bedtools itself does not permit flag-filtering of the bam-file. The script could pre-filter, generating a temporary file, but I think that is best done by the user in order to avoid unexpected complications such as 60Gb of /tmp being filled up for a large BAM file.

**Comment by Acribbs** [comment] 2017-11-15 09:57
Closing issue, please re-open if you think the issue is not solved

**Closed by Acribbs** 2017-11-15 09:57 UTC
